package com.wizinno.pathcloud.wechat.domain;

import com.wizinno.pathcloud.wechat.data.condition.ApplicantCondition;
import com.wizinno.pathcloud.wechat.domain.model.Applicant;

import java.util.List;

public interface ApplicantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Thu May 25 10:52:48 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Thu May 25 10:52:48 CST 2017
     */
    int insert(Applicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Thu May 25 10:52:48 CST 2017
     */
    Applicant selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Thu May 25 10:52:48 CST 2017
     */
    List<Applicant> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table applicant
     *
     * @mbggenerated Thu May 25 10:52:48 CST 2017
     */
    int updateByPrimaryKey(Applicant record);

    List<Applicant> selectByCondition(ApplicantCondition condition);
    Long countByCondition(ApplicantCondition condition);

    int updateUserInfo(Applicant applicant);
}